SurveyProject/Controllers/SuperAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SRV.DataLayer.SuperAdmin;
using SRV.BaseLayer.SuperAdmin;
using SRV.ActionLayer.SuperAdmin;
using SurveyProject.Models;
using System.Data;
using SRV.BaseLayer.Admin;
using SurveyProject.Helper;
using SRV.Utility;
using SRV.BaseLayer.Respondent;
using SRV.ActionLayer.Respondent;
using System.Text;
using System.Data.SqlClient;
using System.Configuration;
using SRV.ActionLayer.Admin;
namespace SurveyProject.Controllers
{
    [CheckLoginAttribute]
    [UnHandledExceptionFilter]
    public class SuperAdminController : Controller
    {
        #region Declaration
        //SuperAdminBase superAdminBase = new SuperAdminBase();
        CreateRoleBase createRoleBase = new CreateRoleBase();
        AdminBase adminBase = new AdminBase();

        ProjectBase projectBase = new ProjectBase();
        SRV.BaseLayer.ActionResult actionResult = new SRV.BaseLayer.ActionResult();
        SRV.ActionLayer.Admin.AdminAction AdminAction = new SRV.ActionLayer.Admin.AdminAction();
        SuperAdminAc superAction = new SuperAdminAc();
        RespondentAction respondentAction = new RespondentAction();
        ProjectSettingsBase projectSettingsBase = new ProjectSettingsBase();
        CommonMethods comMethods = new CommonMethods();
        AdminAction adminAction = new AdminAction();
        #endregion

        #region AdminList Get
        [HttpGet]
        public ActionResult AdminList()
        {
            ManageAdminModel model = new ManageAdminModel();
            List<AdminModel> Adminlist = new List<AdminModel>();
            model.Adminlist = GetAdmins();
            return View(model);
        }
        #endregion

        #region _PartialAdminList Get
        [HttpGet]
        public ActionResult _PartialAdminList()
        {
            ManageAdminModel model = new ManageAdminModel();
            List<AdminModel> Adminlist = new List<AdminModel>();
            model.Adminlist = GetAdmins();
            return View(model);
        }
        #endregion

        #region ProjectList Get
        [HttpGet]
        public ActionResult ProjectList(int id)
        {
            CreateProjectModel model = new CreateProjectModel();
            List<CreateProjectModel> ProjectLst = new List<CreateProjectModel>();
            model.ProjectList = ProjectLst;
            try
            {
                //if (Session["UserId"] != null)
                {
                    int UserId = id;
                    adminBase.Id = UserId;
                    actionResult = AdminAction.Poject_LoadAll(adminBase);

                    if (actionResult.dsResult.Tables[0] != null && actionResult.dsResult.Tables[0].Rows.Count > 0)
                    {
                        foreach (DataRow dr in actionResult.dsResult.Tables[0].Rows)
                        {
                            model = new CreateProjectModel();
                            model.Id = dr["Id"] != DBNull.Value ? Convert.ToInt32(dr["Id"]) : 0;
                            model.ProjectName = dr["ProjectName"] != DBNull.Value ? Convert.ToString(dr["ProjectName"]) : "";
                            model.ProjectQuota = dr["ProjectQuota"] != DBNull.Value ? Convert.ToInt32(dr["ProjectQuota"]) : 0;
                            model.SuperProjectId = dr["SuperProjectId"] != DBNull.Value ? Convert.ToInt32(dr["SuperProjectId"]) : 0;
                            model.SuperProjectName = dr["SuperProjectName"] != DBNull.Value ? Convert.ToString(dr["SuperProjectName"]) : "N/A";
                            model.CreatedOn = dr["CreatedOn"] != DBNull.Value ? Convert.ToDateTime(dr["CreatedOn"]).ToString("MM/dd/yyyy") : "N/A";
                            model.ModifiedOn = dr["ModifiedOn"] != DBNull.Value ? Convert.ToDateTime(dr["ModifiedOn"]).ToString("MM/dd/yyyy") : "N/A";
                            model.CreatedByName = dr["CreatedBy"] != DBNull.Value ? dr["CreatedBy"].ToString() : "N/A";
                            model.ModifiedByName = dr["ModifiedBy"] != DBNull.Value ? dr["ModifiedBy"].ToString() : "N/A";
                            model.CreatedByName = dr["CreatedBy"] != DBNull.Value ? dr["CreatedBy"].ToString() : "N/A";
                            model.ProjectGuid = dr["ProjectGuid"] != DBNull.Value ? dr["ProjectGuid"].ToString() : "N/A";
                            model.Owner = dr["Owner"] != DBNull.Value ? dr["Owner"].ToString() : "N/A";
                            ProjectLst.Add(model);
                        }
                        model.ProjectList = ProjectLst;
                    }



                }
            }
            catch (Exception ex)
            {
                ErrorReporting.WebApplicationError(ex);
            }

            return View(model);
        }
        #endregion

        #region BindState
        public JsonResult BindState(int cId = 0)
        {
            List<SelectListItem> stateLst = new List<SelectListItem>();
            try
            {
                adminBase.CountryId = cId;
                actionResult = AdminAction.State_LoadAll(adminBase);
                if (actionResult.dtResult != null && actionResult.dtResult.Rows.Count > 0)
                {
                    stateLst = actionResult.dtResult.AsEnumerable().Select(dr => new SelectListItem
                    {
                        Text = dr["StateName"] != DBNull.Value ? Convert.ToString(dr["StateName"]) : string.Empty,
                        Value = dr["ID"] != DBNull.Value ? Convert.ToString(dr["ID"]) : string.Empty
                    }).ToList();

                    //foreach (DataRow dr in actionResult.dtResult.Rows)
                    //{
                    //    stateLst.Add(new SelectListItem { Text = dr["StateName"].ToString(), Value = dr["ID"].ToString() });
                    //}
                }
            }
            catch (Exception ex)
            {
                ErrorReporting.WebApplicationError(ex);
            }
            return Json(stateLst, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Register Post
        [AllowAnonymous]
        [HttpPost]
        public ActionResult Register(AdminRegisterModel model)
        {
            try
            {
                adminBase.UserGuid = Guid.NewGuid().ToString();
                adminBase.FirstName = model.FirstName;
                adminBase.LastName = model.LastName;
                adminBase.Gender = model.Gender;
                adminBase.Email = model.Email;
                adminBase.Password = model.Password;
                adminBase.Address = model.Address;
                adminBase.CountryId = Convert.ToInt32(model.CountryId);
                adminBase.StateId = Convert.ToInt32(model.StateId);
                adminBase.City = model.City;
                adminBase.ZipCode = model.ZipCode;
                actionResult = AdminAction.Register_InsertUpdate(adminBase);
                if (actionResult.dtResult != null && actionResult.dtResult.Rows.Count > 0)
                {
                    int status = Convert.ToInt32(actionResult.dtResult.Rows[0][0]);
                    if (status == -10)
                    {
                        TempData["RegErrorMessage"] = "Email Address Already Exists, Please Choose another Email.";
                    }
                    else
                    {
                        //Email.SendConfirmationEmail(adminBase.Email, adminBase.UserGuid);
                        TempData["RegSuccessMessage"] = "You have registered successfully";

                    }

                }
            }
            catch (Exception ex)
            {
                ErrorReporting.WebApplicationError(ex);
            }
            return RedirectToAction("Register");
        }
        #endregion

        #region Register Get
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Register()
        {
            AdminRegisterModel model = new AdminRegisterModel();
            List<SelectListItem> countryLst = new List<SelectListItem>();
            List<SelectListItem> stateLst = new List<SelectListItem>();
            try
            {
                actionResult = AdminAction.Country_LoadAll();
                if (actionResult.dtResult != null && actionResult.dtResult.Rows.Count > 0)
                {
                    foreach (DataRow dr in actionResult.dtResult.Rows)
                    {
                        countryLst.Add(new SelectListItem { Text = dr["CountryName"].ToString(), Value = dr["ID"].ToString() });
                    }
                    model.CountryList = countryLst;
                    model.StateList = stateLst;
                }
            }
            catch (Exception ex)
            {
                ErrorReporting.WebApplicationError(ex);
            }
            return View(model);
        }
        #endregion

        #region UpdateAdminList
        [AllowAnonymous]
        [HttpGet]
        public ActionResult UpdateAdminList()
        {
            ManageAdminModel model = new ManageAdminModel();
            List<AdminModel> Adminlist = new List<AdminModel>();
            model.Adminlist = Adminlist;
            try
            {

                if (Session["UserId"] != null)
                {

                    actionResult = superAction.Admin_AllList();
                    if (actionResult.IsSuccess)
                    {
                        foreach (DataRow dr in actionResult.dtResult.Rows)
                        {
                            if (Convert.ToBoolean(dr["IsDeleted"]) == false)
                            {
                                AdminModel adminModel = new AdminModel();
                                adminModel.Id = Convert.ToInt32(dr["Id"]);
                                adminModel.FirstName = Convert.ToString(dr["FirstName"]);
                                adminModel.LastName = dr["LastName"].ToString();

SurveyProject/Views/SuperAdmin/CreateFieldService.cshtml
@model SurveyProject.Models.AdminModel
@{
    ViewBag.Title = "Create Panel";
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}

<style>
    .btn-danger {
        text-transform: capitalize;
    }
</style>
<div class="questionsection2">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="contentarea2">
                    <div class="surveytitle2">
                        <h5><span data-name="CommonCreate">Create</span> <span data-name="">Field Service</span></h5>
                    </div>
                    <section class="registerForm">
                        @if (TempData["RegErrorMessage"] != null)
                        {
                            <div class="alert alert-danger">@TempData["RegErrorMessage"]</div>
                        }
                        @if (TempData["RegSuccessMessage"] != null)
                        {
                            <div class="alert alert-success">@TempData["RegSuccessMessage"]</div>
                        }
                        @using (Html.BeginForm("CreateFieldService", "SuperAdmin", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            <div class="row">
                                <div class="col-md-3"></div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label data-name="editProfFirstName">First Name</label>
                                        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", tabindex = "1" })
                                        @Html.ValidationMessageFor(m => m.FirstName)
                                    </div>
                                    <div class="form-group">
                                        <label data-name="editProflastName">Last Name</label>
                                        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", tabindex = "2" })
                                        @Html.ValidationMessageFor(m => m.LastName)
                                    </div>
                                    @* <div class="form-group">
                                             @Html.LabelFor(m => m.Gender)<br />
                                                    <div class="row">
                                                        <div class="col-lg-2 col-sm-4" style="margin-right: 10px;">
                                                            <div class="input-group">
                                                                <span class="input-group-addon">
                                                                    @Html.RadioButtonFor(m => m.Gender, true, new { tabindex = "3", id = "male" })
                                                                </span>
                                                                <label class="form-control" for="male">Male</label>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-2 col-sm-2">
                                                            <div class="input-group">
                                                                <span class="input-group-addon">
                                                                    @Html.RadioButtonFor(m => m.Gender, false, new { tabindex = "4", id = "female" })
                                                                </span>
                                                                <label class="form-control" for="female">Female</label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    @Html.ValidationMessageFor(m => m.Gender)
                                        </div>*@

                                    <div class="form-group">
                                        <label data-name="editProfEmail">Email</label>
                                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", tabindex = "4" })
                                        @Html.ValidationMessageFor(m => m.Email)
                                    </div>
                                    <div class="form-group pull-right" style="margin-top: 30px;">
                                        <input type="submit" data-name="CommonCreate" value="Create" class="btn btn-danger" tabindex="5" />
                                    </div>
                                </div>
                                <div class="col-md-3"></div>
                            </div>

                        }
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>

SurveyProject/Views/SuperAdmin/CreateFieldServiceRoles.cshtml
@model SurveyProject.Models.ManageAdminModel
@{
    ViewBag.Title = "Create/Update Roles";
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}
<style>
    .btn-primary {
        text-transform: capitalize;
    }
</style>
<div class="container-fluid">
    @using (Html.BeginForm("CreateFieldServiceRoles", "SuperAdmin", FormMethod.Post))
    {
        <div class="row">

            <div class="form-horizontal" style="margin-top: 15px;">
                @if (TempData["SuccessMessage"] != null)
                {
                    <div class="alert alert-success">@TempData["SuccessMessage"]</div>
                }
                @if (TempData["ErrorMessage"] != null)
                {
                    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
                }
                <div class="form-group">
                    <label data-name="" class="col-md-1 control-label">Panel</label>
                    <div class="col-md-11">
                        @Html.DropDownListFor(m => m.createRoleModel.UserId, Model.createRoleModel.UserList, "Select", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.createRoleModel.UserId)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12 col-sm-12">
                        <p class="checklist">
                            @if (Model.roleList != null && Model.roleList.Count > 0)
                            {
                                foreach (var item in Model.roleList)
                                {
                                    <label for="roleId_@item.RoleId" data-name="@item.RoleName.Replace(" ","_")">@item.RoleName</label>
                                    <input type="checkbox" style="margin-left:10px;" class="roles" id="roleId_@item.RoleId" value="@item.RoleId" onclick="return setRoles(this)" />
                                }
                            }
                        </p>
                        <input type="submit" value="Assign Roles" class="btn btn-primary" style="font-size: 12px;margin-top:50px;  margin-bottom: 15px; margin-left: 50px; text-transform: uppercase;" data-name="SuperAdminAssignRoles" />
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <input type="hidden" id="hdnRoleIds" name="hdnRoleIds" value="" />
            <input type="hidden" id="hdnUserName" name="hdnUserName" value="" />
            <input type="hidden" id="hdnAddEdit" name="hdnAddEdit" value="Add" />
        </div>
    }
</div>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
<script>
    $(document).ready(function () {
        $('#createRoleModel_UserId').on('change', function () {
            $('#hdnUserName').val($("#createRoleModel_UserId option:selected").text());
            var userId = $(this).val();
            if (userId == "") {
                return false;
            }
            clearCheckBoxes();
            $.ajax({
                url: GetPath('/SuperAdmin/ExistingRole'),
                contentType: 'application/json',
                Type: 'GET',
                dataType: 'json',
                data: { UserId: userId },
                async: false,
                success: function (data) {
                    var roleIds = "";
                    if (data.length > 0) {
                        var jsonData = JSON.parse(data);
                        $('[Id*=roleId_]').each(function () {
                            $(this).val($(this).val() + "-0");
                        });
                        for (var i = 0; i <= jsonData.length - 1; i++) {
                            $('#roleId_' + jsonData[i].RoleId + '').prop('checked', 'checked');
                            $('#roleId_' + jsonData[i].RoleId + '').val(jsonData[i].RoleId + "-" + jsonData[i].Id);
                            roleIds += jsonData[i].RoleId + "-" + jsonData[i].Id + ",";
                        }
                        $("#hdnRoleIds").val(roleIds);
                        $("#hdnAddEdit").val("Edit");
                    }
                },
                error: function () {
                    alert("Error occurred");
                },
                complete: function () {
                    //alert($("#hdnRoleIds").val());
                }
            });
        });

        var roleId = '@Session["RoleId"]';
        if (roleId == 1) {
            var language = 'en';
            if (localStorage.getItem('LanguageAbbr') != null) {
                language = localStorage.getItem('LanguageAbbr');
            }
            changeLanguage(language);
        }
    });

    function setRoles(caller) {
        if (caller.checked) {
            // Set names in hidden field
            var roleIds = $("#hdnRoleIds").val();
            if (roleIds.length > 0) {
                $("#hdnRoleIds").val(roleIds + $(caller).val() + ",");
            }
            else {
                $("#hdnRoleIds").val($(caller).val() + ",");
            }
        }
        else {
            // Reset names in hidden field
            var roleIds = $("#hdnRoleIds").val();
            roleIds = roleIds.replace($(caller).val() + ",", '');
            $("#hdnRoleIds").val(roleIds);
        }
    }

    function clearCheckBoxes() {
        $('input').each(function () {
            if ($(this).attr('type') == 'checkbox')
                $(this).removeAttr('checked');
        });
    }
</script>

SurveyProject/Views/SuperAdmin/CreatePanel.cshtml
@model SurveyProject.Models.AdminModel
@{
    ViewBag.Title = "Create Panel";
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}

<style>
    .btn-danger {
        text-transform: capitalize;
    }
</style>
<div class="questionsection2">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="contentarea2">
                    <div class="surveytitle2">
                        <h5><span data-name="CommonCreate">Create</span> <span data-name="">Panel</span></h5>
                    </div>
                    <section class="registerForm">
                        @if (TempData["RegErrorMessage"] != null)
                        {
                            <div class="alert alert-danger">@TempData["RegErrorMessage"]</div>
                        }
                        @if (TempData["RegSuccessMessage"] != null)
                        {
                            <div class="alert alert-success">@TempData["RegSuccessMessage"]</div>
                        }
                        @using (Html.BeginForm("CreatePanel", "SuperAdmin", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            <div class="row">
                                <div class="col-md-3"></div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label data-name="editProfFirstName">First Name</label>
                                        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", tabindex = "1" })
                                        @Html.ValidationMessageFor(m => m.FirstName)
                                    </div>
                                    <div class="form-group">
                                        <label data-name="editProflastName">Last Name</label>
                                        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", tabindex = "2" })
                                        @Html.ValidationMessageFor(m => m.LastName)
                                    </div>
                                    @* <div class="form-group">
                                             @Html.LabelFor(m => m.Gender)<br />
                                                    <div class="row">
                                                        <div class="col-lg-2 col-sm-4" style="margin-right: 10px;">
                                                            <div class="input-group">
                                                                <span class="input-group-addon">
                                                                    @Html.RadioButtonFor(m => m.Gender, true, new { tabindex = "3", id = "male" })
                                                                </span>
                                                                <label class="form-control" for="male">Male</label>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-2 col-sm-2">
                                                            <div class="input-group">
                                                                <span class="input-group-addon">
                                                                    @Html.RadioButtonFor(m => m.Gender, false, new { tabindex = "4", id = "female" })
                                                                </span>
                                                                <label class="form-control" for="female">Female</label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    @Html.ValidationMessageFor(m => m.Gender)
                                        </div>*@

                                    <div class="form-group">
                                        <label data-name="editProfEmail">Email</label>
                                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", tabindex = "4" })
                                        @Html.ValidationMessageFor(m => m.Email)
                                    </div>
                                    <div class="form-group pull-right" style="margin-top: 30px;">
                                        <input type="submit" data-name="CommonCreate" value="Create" class="btn btn-danger" tabindex="5" />
                                    </div>
                                </div>
                                <div class="col-md-3"></div>
                            </div>

                        }
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>

SurveyProject/Views/SuperAdmin/CreateUser.cshtml
@model SurveyProject.Models.AdminModel
@{
    ViewBag.Title = "Create User";
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}

<style>
    .btn-danger {
        text-transform: capitalize;
    }
</style>
<div class="questionsection2">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="contentarea2">
                    <div class="surveytitle2">
                        <h5><span data-name="CommonCreate">Create</span> <span data-name="SurveyResponsesUser">Users</span></h5>
                    </div>
                    <section class="registerForm">
                        @if (TempData["RegErrorMessage"] != null)
                        {
                            <div class="alert alert-danger">@TempData["RegErrorMessage"]</div>
                        }
                        @if (TempData["RegSuccessMessage"] != null)
                        {
                            <div class="alert alert-success">@TempData["RegSuccessMessage"]</div>
                        }
                        @using (Html.BeginForm("CreateUser", "SuperAdmin", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            <div class="row">
                                <div class="col-md-3"></div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label data-name="editProfFirstName">First Name</label>
                                        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", tabindex = "1" })
                                        @Html.ValidationMessageFor(m => m.FirstName)
                                    </div>
                                    <div class="form-group">
                                        <label data-name="editProflastName">Last Name</label>
                                        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", tabindex = "2" })
                                        @Html.ValidationMessageFor(m => m.LastName)
                                    </div>
                                    @* <div class="form-group">
                                             @Html.LabelFor(m => m.Gender)<br />
                                                    <div class="row">
                                                        <div class="col-lg-2 col-sm-4" style="margin-right: 10px;">
                                                            <div class="input-group">
                                                                <span class="input-group-addon">
                                                                    @Html.RadioButtonFor(m => m.Gender, true, new { tabindex = "3", id = "male" })
                                                                </span>
                                                                <label class="form-control" for="male">Male</label>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-2 col-sm-2">
                                                            <div class="input-group">
                                                                <span class="input-group-addon">
                                                                    @Html.RadioButtonFor(m => m.Gender, false, new { tabindex = "4", id = "female" })
                                                                </span>
                                                                <label class="form-control" for="female">Female</label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    @Html.ValidationMessageFor(m => m.Gender)
                                        </div>*@

                                    <div class="form-group">
                                        <label data-name="editProfEmail">Email</label>
                                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", tabindex = "4" })
                                        @Html.ValidationMessageFor(m => m.Email)
                                    </div>
                                    <div class="form-group pull-right" style="margin-top: 30px;">
                                        <input type="submit" data-name="CommonCreate" value="Create" class="btn btn-danger" tabindex="5" />
                                    </div>
                                </div>
                                <div class="col-md-3"></div>
                            </div>

                        }
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>